meta:
  url:
  title: Darkdown
  description: Markdown を 黒塗りできる Monadic Parser
  siteName:
  sns: ["twitter"]
slide:
  loop: false
  ui:
    sidebar: true
    vertical: false
    pagination: # bullets | progressbar | fraction
    effect: # fade | cube | flip
  code:
    # https://prismjs.com/
    plugins: []
    theme: default # coy | dark | funky | okaidia | solarizedlight | tomorrow | twilight
